# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170120_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(blank=True, default='abc', max_length=15, unique=True),
        ),
    ]
